# Setup

title: Sigvald Marholm
email: sigvald@marebakken.com
description: Computational Physicist
baseurl: ""
url: ""
github_username: sigvaldm

author:
  name: Sigvald Marholm

# Build settings

markdown: kramdown
highlighter: rouge

theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

plugins:
  - jekyll-feed
  - jekyll-paginate

# Sidebar settings
sidebar_home_link:  true
sidebar_blog_link:  '/blog/'   # By default, your home page is your blog

paginate_path: "/blog/page:num"
paginate: 5

